# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:   [ROLE_USER, ROLE_MODERATOR]
        ROLE_MODERATOR: [ROLE_USER]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: 'test', roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#            # this firewall applies to all URLs
#            pattern: ^/

            # activate different ways to authenticate
            anonymous: ~

            form_login:
                login_path: cabinet_login
                check_path: cabinet_login

            logout:
                # The route name the user can go to in order to logout
                path: cabinet_logout
                # The name of the route to redirect to after logging out
                target: plug
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
